import type { NodeTypeDefinition } from './index';

export const NODE_TYPE_REGISTRY: Record<string, NodeTypeDefinition> = {
  agent: {
    type: 'agent',
    label: 'Agent',
    description: 'An AI agent that can reason, plan, and use tools',
    category: 'ai',
    icon: 'Bot',
    color: 'violet',
    defaultConfig: {
      model: 'claude-opus-4-6',
      systemPrompt: 'You are a helpful assistant.',
      temperature: 0.7,
      maxTokens: 4096,
      tools: [],
      memory: false,
    },
    handles: [
      { id: 'in', type: 'target', position: 'top', label: 'Input' },
      { id: 'out', type: 'source', position: 'bottom', label: 'Output' },
    ],
    minConnections: 1,
  },
  input: {
    type: 'input',
    label: 'Input',
    description: 'Entry point for data into the workflow',
    category: 'io',
    icon: 'LogIn',
    color: 'emerald',
    defaultConfig: {
      label: 'User Input',
      description: '',
      inputType: 'text',
      required: true,
      defaultValue: '',
    },
    handles: [
      { id: 'out', type: 'source', position: 'bottom', label: 'Output' },
    ],
  },
  output: {
    type: 'output',
    label: 'Output',
    description: 'Final output or response of the workflow',
    category: 'io',
    icon: 'LogOut',
    color: 'blue',
    defaultConfig: {
      label: 'Result',
      outputType: 'text',
      format: '',
    },
    handles: [
      { id: 'in', type: 'target', position: 'top', label: 'Input' },
    ],
  },
  condition: {
    type: 'condition',
    label: 'Condition',
    description: 'Branch the flow based on a boolean expression',
    category: 'logic',
    icon: 'GitBranch',
    color: 'amber',
    defaultConfig: {
      expression: '',
      trueLabel: 'True',
      falseLabel: 'False',
      language: 'jinja2',
    },
    handles: [
      { id: 'in', type: 'target', position: 'top', label: 'Input' },
      { id: 'true', type: 'source', position: 'right', label: 'True' },
      { id: 'false', type: 'source', position: 'bottom', label: 'False' },
    ],
  },
  router: {
    type: 'router',
    label: 'Router',
    description: 'Route to one of many paths based on conditions',
    category: 'logic',
    icon: 'Network',
    color: 'orange',
    defaultConfig: {
      routes: [
        { id: 'route-1', label: 'Route 1', condition: '' },
        { id: 'route-2', label: 'Route 2', condition: '' },
      ],
      defaultRoute: 'route-1',
    },
    handles: [
      { id: 'in', type: 'target', position: 'top', label: 'Input' },
      { id: 'route-1', type: 'source', position: 'bottom', label: 'Route 1' },
      { id: 'route-2', type: 'source', position: 'right', label: 'Route 2' },
    ],
  },
  tool: {
    type: 'tool',
    label: 'Tool',
    description: 'Execute a specific tool or function',
    category: 'integration',
    icon: 'Wrench',
    color: 'cyan',
    defaultConfig: {
      toolName: '',
      toolType: 'builtin',
      description: '',
      parameters: {},
    },
    handles: [
      { id: 'in', type: 'target', position: 'top', label: 'Input' },
      { id: 'out', type: 'source', position: 'bottom', label: 'Output' },
    ],
  },
  memory: {
    type: 'memory',
    label: 'Memory',
    description: 'Read or write to agent memory store',
    category: 'memory',
    icon: 'Database',
    color: 'purple',
    defaultConfig: {
      memoryType: 'short_term',
      operation: 'read',
      namespace: 'default',
    },
    handles: [
      { id: 'in', type: 'target', position: 'top', label: 'Input' },
      { id: 'out', type: 'source', position: 'bottom', label: 'Output' },
    ],
  },
  api_call: {
    type: 'api_call',
    label: 'API Call',
    description: 'Make an HTTP request to an external service',
    category: 'integration',
    icon: 'Globe',
    color: 'teal',
    defaultConfig: {
      method: 'GET',
      url: '',
      headers: {},
      bodyTemplate: '',
      authType: 'none',
      authValue: '',
      timeoutMs: 30000,
    },
    handles: [
      { id: 'in', type: 'target', position: 'top', label: 'Input' },
      { id: 'out', type: 'source', position: 'bottom', label: 'Response' },
      { id: 'error', type: 'source', position: 'right', label: 'Error' },
    ],
  },
  prompt: {
    type: 'prompt',
    label: 'Prompt',
    description: 'Format a prompt template with dynamic variables',
    category: 'ai',
    icon: 'MessageSquare',
    color: 'indigo',
    defaultConfig: {
      template: '',
      language: 'jinja2',
      outputVariable: 'prompt',
    },
    handles: [
      { id: 'in', type: 'target', position: 'top', label: 'Input' },
      { id: 'out', type: 'source', position: 'bottom', label: 'Prompt' },
    ],
  },
  approval: {
    type: 'approval',
    label: 'Approval',
    description: 'Pause and wait for human approval before continuing',
    category: 'control',
    icon: 'UserCheck',
    color: 'rose',
    defaultConfig: {
      message: 'Please review and approve to continue',
      approvers: [],
      timeoutHours: 24,
      onTimeout: 'reject',
    },
    handles: [
      { id: 'in', type: 'target', position: 'top', label: 'Input' },
      { id: 'approved', type: 'source', position: 'bottom', label: 'Approved' },
      { id: 'rejected', type: 'source', position: 'right', label: 'Rejected' },
    ],
  },
  loop: {
    type: 'loop',
    label: 'Loop',
    description: 'Repeat a sequence for each item or until a condition',
    category: 'control',
    icon: 'RefreshCw',
    color: 'sky',
    defaultConfig: {
      loopType: 'for_each',
      iterableVar: 'items',
      condition: '',
      maxIterations: 100,
      itemVar: 'item',
    },
    handles: [
      { id: 'in', type: 'target', position: 'top', label: 'Input' },
      { id: 'body', type: 'source', position: 'right', label: 'Loop Body' },
      { id: 'out', type: 'source', position: 'bottom', label: 'Done' },
    ],
  },
  group: {
    type: 'group',
    label: 'Group',
    description: 'Visually group related nodes together',
    category: 'control',
    icon: 'Square',
    color: 'slate',
    defaultConfig: {
      label: 'Group',
      color: '#94a3b8',
      collapsed: false,
      nodeIds: [],
    },
    handles: [],
    canHaveChildren: true,
  },
};

export const NODE_CATEGORIES = {
  io: { label: 'Input / Output', order: 0 },
  ai: { label: 'AI & Agents', order: 1 },
  logic: { label: 'Logic & Flow', order: 2 },
  integration: { label: 'Integrations', order: 3 },
  memory: { label: 'Memory', order: 4 },
  control: { label: 'Control', order: 5 },
} as const;
